Repository ember-codemods/ember-native-class-codemod, pull requests merged in 2023-03, with the labels that each got.

#519 Remove node 12 from package.json engines / Upgrade release-it dependencies
  package.json
  yarn.lock
Labels: dependencies

#211 Don't append object name when type is already at the end of the filename
  transforms/ember-object/__testfixtures__/-mock-telemetry.json
  transforms/ember-object/__testfixtures__/injecting-service.output.js
  transforms/ember-object/__testfixtures__/types/services/some-service.input.js
  transforms/ember-object/__testfixtures__/types/services/some-service.output.js
  transforms/helpers/parse-helper.ts
Labels: bug

#520 Handle 'true'/'false' stringified boolean options and better config error handling
  README.md
  test/helpers/expect-logs.ts
  test/options.test.ts
  transforms/ember-object/__testfixtures__/options/string-boolean.input.js
  transforms/ember-object/__testfixtures__/options/string-boolean.options.json
  transforms/ember-object/__testfixtures__/options/string-boolean.output.js
  transforms/ember-object/index.ts
  transforms/helpers/options.ts
  transforms/helpers/schema-helper.ts
  tsconfig.lint.json
Labels: bug, enhancement
